/**
 * Data Structures & Algorithms question bank.
 *
 * Rows are [question, correct answer, ...wrong answers], grouped by difficulty.
 * The question text is the sync key: seeding inserts texts it has not seen and
 * moves existing ones to the difficulty listed here, so never reword a question
 * that is already live (it would be inserted again as a new one).
 *
 * Difficulty guide:
 *  1. Recognise the basic structures and vocabulary (stack, queue, tree, Big-O names).
 *  2. Big-O of everyday operations, simple searches and traversals.
 *  3. Sorting, heaps, BSTs, hashing internals, recursion and core techniques.
 *  4. Graph algorithms, balanced trees, amortized analysis, classic DP.
 *  5. Advanced structures and algorithms, recurrences and complexity theory.
 */
export const DSA_QUESTIONS: Record<number, string[][]> = {
  1: [
    [
      'Which data structure is Last-In-First-Out (LIFO)?',
      'Stack',
      'Queue',
      'Linked list',
      'Heap',
    ],
    [
      'Which data structure is First-In-First-Out (FIFO)?',
      'Queue',
      'Stack',
      'Binary tree',
      'Hash set',
    ],
    [
      'Time complexity of reading an array element by index?',
      'O(1)',
      'O(n)',
      'O(log n)',
      'O(n log n)',
    ],
    [
      'What is the index of the first element in a zero-indexed array?',
      '0',
      '1',
      '-1',
      'It depends on the length',
    ],
    [
      'Which operation adds an element to the top of a stack?',
      'Push',
      'Pop',
      'Peek',
      'Enqueue',
    ],
    [
      'In a singly linked list, each node points to...',
      'The next node',
      'The previous node',
      'The head node',
      'Both neighbours',
    ],
    [
      'What does a hash map store?',
      'Key-value pairs',
      'Only sorted values',
      'Keys without values',
      'A FIFO sequence',
    ],
    [
      'At most, how many children does a node in a binary tree have?',
      '2',
      '1',
      '3',
      'Unlimited',
    ],
    [
      'Worst-case time complexity of linear search?',
      'O(n)',
      'O(1)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Which operation removes the top element of a stack?',
      'Pop',
      'Push',
      'Enqueue',
      'Insert',
    ],
    [
      'Which operation adds an element to the back of a queue?',
      'Enqueue',
      'Dequeue',
      'Pop',
      'Peek',
    ],
    [
      'What is the topmost node of a tree called?',
      'Root',
      'Leaf',
      'Edge',
      'Sibling',
    ],
    [
      'A tree node with no children is called a...',
      'Leaf',
      'Root',
      'Edge',
      'Branch',
    ],
    [
      'How are array elements laid out in memory?',
      'Contiguously',
      'At random addresses',
      'As a tree',
      'As key-value pairs',
    ],
    [
      'What does peek do on a stack?',
      'Returns the top without removing it',
      'Removes the top element',
      'Adds an element on top',
      'Empties the stack',
    ],
    [
      'Index of the last element in a zero-indexed array of length n?',
      'n - 1',
      'n',
      'n + 1',
      '1',
    ],
    [
      'In a graph, a connection between two nodes is called...',
      'An edge',
      'A vertex',
      'A leaf',
      'A root',
    ],
    [
      'In a graph, a node is also called a...',
      'Vertex',
      'Edge',
      'Weight',
      'Path',
    ],
    [
      'Which structure keeps only unique values?',
      'Set',
      'List',
      'Stack',
      'Queue',
    ],
    [
      'What does the head of a linked list refer to?',
      'The first node',
      'The last node',
      'The middle node',
      'The largest value',
    ],
    [
      'What does O(1) time mean?',
      'Constant time',
      'Linear time',
      'Logarithmic time',
      'Quadratic time',
    ],
    [
      'Which name describes O(n) growth?',
      'Linear',
      'Constant',
      'Logarithmic',
      'Exponential',
    ],
    [
      "Which structure best fits an editor's undo history?",
      'Stack',
      'Queue',
      'Hash set',
      'Binary heap',
    ],
    [
      'Print jobs handled in the order they were sent form a...',
      'Queue',
      'Stack',
      'Tree',
      'Set',
    ],
    [
      'Which part of a recursive function stops it calling itself forever?',
      'Base case',
      'Recursive case',
      'Loop counter',
      'Return type',
    ],
    [
      'A node in a doubly linked list links to...',
      'Both the next and previous nodes',
      'Only the next node',
      'Only the head',
      'Every other node',
    ],
    [
      'A two-dimensional array is best described as...',
      'An array of arrays',
      'A linked list of stacks',
      'A hash map of keys',
      'A binary tree',
    ],
    [
      'Which of these is a linear data structure?',
      'Queue',
      'Binary tree',
      'Graph',
      'Trie',
    ],
    [
      'Which of these is a non-linear data structure?',
      'Tree',
      'Array',
      'Stack',
      'Queue',
    ],
    [
      'Adding an element to the end of a list is called...',
      'Appending',
      'Popping',
      'Peeking',
      'Dequeuing',
    ],
    [
      'Removing an element from the front of a queue is called...',
      'Dequeue',
      'Enqueue',
      'Push',
      'Append',
    ],
    [
      'Which structure is a chain of nodes connected by pointers?',
      'Linked list',
      'Array',
      'Hash table',
      'Matrix',
    ],
    [
      'How many elements does an empty stack hold?',
      '0',
      '1',
      '-1',
      'Undefined',
    ],
    [
      'Popping from an empty stack causes...',
      'An underflow',
      'An overflow',
      'A hash collision',
      'A rotation',
    ],
    [
      'Pushing onto a full fixed-size stack causes...',
      'An overflow',
      'An underflow',
      'A hash collision',
      'A rotation',
    ],
    [
      'Which structure best models friendships in a social network?',
      'Graph',
      'Stack',
      'Queue',
      'Array of numbers',
    ],
    [
      'Which structure best models a company org chart?',
      'Tree',
      'Queue',
      'Stack',
      'Hash set',
    ],
    [
      "A node's direct descendant in a tree is called its...",
      'Child',
      'Parent',
      'Ancestor',
      'Root',
    ],
    [
      'Nodes that share the same parent are called...',
      'Siblings',
      'Leaves',
      'Roots',
      'Edges',
    ],
    [
      'In a graph, a sequence of edges joining vertices is a...',
      'Path',
      'Leaf',
      'Key',
      'Bucket',
    ],
    [
      'A path that starts and ends at the same vertex is a...',
      'Cycle',
      'Tree',
      'Leaf',
      'Root',
    ],
    [
      'What does a hash function turn a key into?',
      'A bucket index',
      'A sorted list',
      'A tree node',
      'A queue',
    ],
    [
      'Which structure lets you jump straight to any element by position?',
      'Array',
      'Linked list',
      'Queue',
      'Stack',
    ],
    [
      'What does n usually stand for in Big-O notation?',
      'The input size',
      'The number of CPUs',
      'The runtime in seconds',
      'A memory address',
    ],
    [
      'What is O(n²) growth called?',
      'Quadratic',
      'Linear',
      'Logarithmic',
      'Constant',
    ],
    [
      'What is O(log n) growth called?',
      'Logarithmic',
      'Linear',
      'Quadratic',
      'Exponential',
    ],
    [
      'A function that calls itself is called...',
      'Recursive',
      'Iterative',
      'Constant',
      'Static',
    ],
    [
      'Which structure lets you add and remove at both ends?',
      'Deque',
      'Stack',
      'Set',
      'Binary tree',
    ],
    [
      'Which structure is a grid of rows and columns?',
      'Matrix',
      'Linked list',
      'Stack',
      'Trie',
    ],
    [
      'Keys in a hash map must be...',
      'Unique',
      'Sorted',
      'Negative',
      'Strings only',
    ],
    [
      'How many valid indexes does an array of 10 elements have?',
      '10',
      '9',
      '11',
      '1',
    ],
    [
      'Which structure tracks function calls while a program runs?',
      'The call stack',
      'A queue',
      'A hash map',
      'A trie',
    ],
    [
      "Which structure fits a browser's back button?",
      'Stack',
      'Queue',
      'Heap',
      'Set',
    ],
    [
      'The number of elements in a collection is its...',
      'Size',
      'Index',
      'Key',
      'Height',
    ],
    [
      'Which structure always serves the highest-priority item first?',
      'Priority queue',
      'Stack',
      'Linked list',
      'Set',
    ],
    [
      'A variable that stores a memory address is a...',
      'Pointer',
      'Stack',
      'Leaf',
      'Bucket',
    ],
    [
      "Big-O notation describes an algorithm's...",
      'Growth as the input gets bigger',
      'Exact runtime in seconds',
      'Memory address',
      'Programming language',
    ],
  ],
  2: [
    [
      'Binary search requires the input to be...',
      'Sorted',
      'Unique',
      'A linked list',
      'Of even length',
    ],
    [
      'Time complexity of binary search on a sorted array?',
      'O(log n)',
      'O(n)',
      'O(1)',
      'O(n log n)',
    ],
    [
      'Average time complexity of a hash table lookup?',
      'O(1)',
      'O(log n)',
      'O(n)',
      'O(n log n)',
    ],
    [
      'Which traversal visits a binary search tree in sorted order?',
      'In-order',
      'Pre-order',
      'Post-order',
      'Level-order',
    ],
    [
      'Time to insert at the head of a singly linked list?',
      'O(1)',
      'O(n)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Which data structure drives a breadth-first search?',
      'Queue',
      'Stack',
      'Heap',
      'Trie',
    ],
    [
      'Which data structure drives an iterative depth-first search?',
      'Stack',
      'Queue',
      'Hash map',
      'Priority queue',
    ],
    [
      'What is a hash collision?',
      'Two keys map to the same bucket',
      'A key inserted twice',
      'An empty table lookup',
      'A deleted key',
    ],
    [
      'In a min-heap, the root holds...',
      'The smallest element',
      'The largest element',
      'The median',
      'The newest element',
    ],
    [
      'Time to push onto a stack built on a linked list?',
      'O(1)',
      'O(n)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Time to find a value in an unsorted linked list?',
      'O(n)',
      'O(1)',
      'O(log n)',
      'O(n log n)',
    ],
    [
      'Worst-case time to reach the i-th node of a linked list?',
      'O(n)',
      'O(1)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Time complexity of two nested loops over n items each?',
      'O(n²)',
      'O(n)',
      'O(log n)',
      'O(n log n)',
    ],
    [
      'Each step of binary search discards about...',
      'Half the remaining items',
      'One item',
      'A quarter of the items',
      'All but one item',
    ],
    [
      'Which traversal visits the root before its subtrees?',
      'Pre-order',
      'In-order',
      'Post-order',
      'Reverse in-order',
    ],
    [
      'Which traversal visits the root after both subtrees?',
      'Post-order',
      'Pre-order',
      'In-order',
      'Level-order',
    ],
    [
      'Level-order traversal of a tree is the same as...',
      'Breadth-first search',
      'Depth-first search',
      'In-order traversal',
      'Binary search',
    ],
    [
      'Time to remove the first element of an array by shifting the rest?',
      'O(n)',
      'O(1)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Time to dequeue from a well-implemented queue?',
      'O(1)',
      'O(n)',
      'O(log n)',
      'O(n log n)',
    ],
    [
      "In a binary search tree, keys in a node's left subtree are...",
      'Smaller than the node',
      'Larger than the node',
      'Equal to the node',
      'In random order',
    ],
    [
      'A recursive function with no base case usually ends in...',
      'A stack overflow',
      'Faster execution',
      'A syntax error',
      'Memory being freed early',
    ],
    [
      'Which of these grows the slowest?',
      'O(log n)',
      'O(n)',
      'O(n log n)',
      'O(n²)',
    ],
    [
      'Which of these grows the fastest?',
      'O(2ⁿ)',
      'O(n³)',
      'O(n²)',
      'O(n log n)',
    ],
    ['Simplify O(3n² + 5n + 2).', 'O(n²)', 'O(n)', 'O(n³)', 'O(1)'],
    [
      'In an undirected graph, the degree of a vertex is...',
      'The number of edges touching it',
      'Its distance from the root',
      'The number of vertices in the graph',
      'Its edge weight',
    ],
    [
      'Which is faster on average for membership checks?',
      'A hash set',
      'An unsorted list',
      'They are always equal',
      'It depends only on the element type',
    ],
    [
      'Time to find the maximum of an unsorted array?',
      'O(n)',
      'O(1)',
      'O(log n)',
      'O(n log n)',
    ],
    [
      'Which sort repeatedly swaps adjacent out-of-order elements?',
      'Bubble sort',
      'Merge sort',
      'Quicksort',
      'Heapsort',
    ],
    [
      'Worst-case time complexity of bubble sort?',
      'O(n²)',
      'O(n log n)',
      'O(n)',
      'O(log n)',
    ],
    [
      'Time complexity of a loop that halves n on every iteration?',
      'O(log n)',
      'O(n)',
      'O(n²)',
      'O(1)',
    ],
    [
      'A graph whose edges have a direction is called...',
      'Directed',
      'Undirected',
      'Weighted',
      'Complete',
    ],
    [
      'Time to append to a linked list that keeps a tail pointer?',
      'O(1)',
      'O(n)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Time to append to a singly linked list with no tail pointer?',
      'O(n)',
      'O(1)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Time to delete a node from a doubly linked list given a pointer to it?',
      'O(1)',
      'O(n)',
      'O(log n)',
      'O(n log n)',
    ],
    [
      'Time to insert into the middle of an array by shifting elements?',
      'O(n)',
      'O(1)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Space complexity of an array of n elements?',
      'O(n)',
      'O(1)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Time of one loop from 1 to n doing O(1) work per step?',
      'O(n)',
      'O(1)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Three nested loops over n items each run in...',
      'O(n³)',
      'O(n²)',
      'O(n log n)',
      'O(2ⁿ)',
    ],
    [
      'Two loops over n items, one after the other, run in...',
      'O(n)',
      'O(n²)',
      'O(log n)',
      'O(2ⁿ)',
    ],
    [
      'Best-case time complexity of linear search?',
      'O(1)',
      'O(n)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Time to check whether a stack is empty?',
      'O(1)',
      'O(n)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Which structure gives O(1) average lookup by key?',
      'Hash map',
      'Sorted array',
      'Linked list',
      'Binary search tree',
    ],
    [
      'Which search works on an unsorted array?',
      'Linear search',
      'Binary search',
      'Interpolation search',
      'Exponential search',
    ],
    [
      'Which sort inserts each element into place in a growing sorted part?',
      'Insertion sort',
      'Selection sort',
      'Bubble sort',
      'Heapsort',
    ],
    [
      'Worst-case time complexity of insertion sort?',
      'O(n²)',
      'O(n)',
      'O(n log n)',
      'O(log n)',
    ],
    [
      'Worst-case time complexity of selection sort?',
      'O(n²)',
      'O(n)',
      'O(n log n)',
      'O(log n)',
    ],
    [
      'In a max-heap, the root holds...',
      'The largest element',
      'The smallest element',
      'The median',
      'The oldest element',
    ],
    [
      'What does DFS do when it reaches a dead end?',
      'Backtracks to the last unexplored branch',
      'Restarts from the start vertex',
      'Stops the search',
      'Visits the next level',
    ],
    [
      'BFS visits vertices in order of their...',
      'Number of edges from the start',
      'Alphabetical label',
      'Edge weights',
      'Degree',
    ],
    [
      'What usually tracks visited vertices in a graph search?',
      'A set or boolean array',
      'A trie',
      'A priority queue',
      'A second graph',
    ],
    [
      'At each node, a BST lookup compares the target to decide...',
      'Whether to go left or right',
      'Which bucket to use',
      'Whether to rotate',
      'Which level to print',
    ],
    [
      'An adjacency list stores, for each vertex...',
      'Its neighbours',
      'Its parent',
      'Its shortest path',
      'Its height',
    ],
    [
      'Worst-case time to search a sorted linked list?',
      'O(n)',
      'O(log n)',
      'O(1)',
      'O(n log n)',
    ],
    ['Time to reverse an array in place?', 'O(n)', 'O(1)', 'O(log n)', 'O(n²)'],
  ],
  3: [
    [
      'Worst-case time complexity of quicksort?',
      'O(n²)',
      'O(n log n)',
      'O(n)',
      'O(log n)',
    ],
    [
      'Time complexity of merge sort in every case?',
      'O(n log n)',
      'O(n²)',
      'O(n)',
      'O(log n)',
    ],
    [
      'Time to insert into a binary heap of n elements?',
      'O(log n)',
      'O(1)',
      'O(n)',
      'O(n log n)',
    ],
    [
      'Worst-case search time in an unbalanced binary search tree?',
      'O(n)',
      'O(log n)',
      'O(1)',
      'O(n log n)',
    ],
    [
      'Which of these sorting algorithms is stable?',
      'Merge sort',
      'Quicksort',
      'Heapsort',
      'Selection sort',
    ],
    [
      'Extra space used by merge sort on an array?',
      'O(n)',
      'O(1)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Height of a balanced binary search tree with n nodes?',
      'O(log n)',
      'O(n)',
      'O(1)',
      'O(√n)',
    ],
    [
      'Which data structure is best for string prefix lookups?',
      'Trie',
      'Hash map',
      'Min-heap',
      'Queue',
    ],
    [
      'Which technique stores results of overlapping subproblems?',
      'Dynamic programming',
      'Greedy',
      'Divide and conquer',
      'Backtracking',
    ],
    [
      'Best-case time complexity of insertion sort?',
      'O(n)',
      'O(n²)',
      'O(log n)',
      'O(n log n)',
    ],
    [
      'Average time complexity of quicksort?',
      'O(n log n)',
      'O(n²)',
      'O(n)',
      'O(log n)',
    ],
    [
      'Which sort picks a pivot and partitions around it?',
      'Quicksort',
      'Merge sort',
      'Insertion sort',
      'Counting sort',
    ],
    [
      'Which sort repeatedly selects the minimum of the unsorted part?',
      'Selection sort',
      'Insertion sort',
      'Bubble sort',
      'Merge sort',
    ],
    [
      'Time to read the minimum of a min-heap without removing it?',
      'O(1)',
      'O(log n)',
      'O(n)',
      'O(n log n)',
    ],
    [
      'Time to remove the minimum from a binary min-heap?',
      'O(log n)',
      'O(1)',
      'O(n)',
      'O(n log n)',
    ],
    [
      'In a 0-indexed array heap, the children of index i are at...',
      '2i + 1 and 2i + 2',
      'i + 1 and i + 2',
      '2i and 2i + 1',
      'i / 2 and i / 2 + 1',
    ],
    [
      'Which collision strategy keeps a list of keys in each bucket?',
      'Separate chaining',
      'Linear probing',
      'Double hashing',
      'Quadratic probing',
    ],
    [
      "A hash table's load factor is...",
      'Entries divided by buckets',
      'Buckets divided by entries',
      'The number of collisions',
      'The size of a hash value',
    ],
    [
      'Which structure implements a priority queue efficiently?',
      'Binary heap',
      'Stack',
      'Unsorted linked list',
      'Queue',
    ],
    [
      'Average search time in a BST built from random insertions?',
      'O(log n)',
      'O(1)',
      'O(n)',
      'O(n log n)',
    ],
    [
      'Which sort is fastest on nearly sorted input?',
      'Insertion sort',
      'Selection sort',
      'Heapsort',
      'Quicksort with a first-element pivot',
    ],
    ['Time complexity of heapsort?', 'O(n log n)', 'O(n²)', 'O(n)', 'O(log n)'],
    [
      'Extra space used by heapsort on an array?',
      'O(1)',
      'O(n)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Naive recursive Fibonacci runs in...',
      'Exponential time',
      'Linear time',
      'Logarithmic time',
      'Constant time',
    ],
    [
      'Which technique makes the locally best choice at each step?',
      'Greedy',
      'Dynamic programming',
      'Backtracking',
      'Brute force',
    ],
    [
      'Deleting a BST node with two children usually replaces it with its...',
      'In-order successor',
      'Parent',
      'Root',
      'Left sibling',
    ],
    [
      'Which sort runs in O(n + k) for integers from 0 to k?',
      'Counting sort',
      'Merge sort',
      'Quicksort',
      'Heapsort',
    ],
    [
      'Call stack space of a recursion n levels deep?',
      'O(n)',
      'O(1)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Time to find a pair with a target sum in a sorted array using two pointers?',
      'O(n)',
      'O(n²)',
      'O(log n)',
      'O(n log n)',
    ],
    [
      'Total work of 1 + 2 + 3 + ... + n operations?',
      'O(n²)',
      'O(n)',
      'O(n log n)',
      'O(log n)',
    ],
    [
      'Which algorithm finds shortest paths in an unweighted graph?',
      'BFS',
      'DFS',
      "Prim's",
      "Kruskal's",
    ],
    [
      'Maximum number of nodes at depth d of a binary tree (root at depth 0)?',
      '2ᵈ',
      'd',
      '2d',
      'd²',
    ],
    [
      'Maximum number of nodes in a binary tree of height h (a lone root has height 0)?',
      '2ʰ⁺¹ - 1',
      '2ʰ',
      'h²',
      '2h + 1',
    ],
    [
      'Which of these sorts is not comparison-based?',
      'Radix sort',
      'Merge sort',
      'Quicksort',
      'Heapsort',
    ],
    [
      'Radix sort processes numbers...',
      'Digit by digit',
      'Around a pivot',
      'Through a heap',
      'By swapping neighbours',
    ],
    [
      'Which technique tries choices and undoes them when they fail?',
      'Backtracking',
      'Greedy',
      'Memoization',
      'Hashing',
    ],
    [
      'Which problem is a classic backtracking exercise?',
      'N-Queens',
      'Finding an array maximum',
      'Reversing a string',
      'Summing an array',
    ],
    [
      'Linear probing handles a collision by...',
      'Trying the next slot',
      'Chaining a list in the bucket',
      'Dropping the key',
      'Sorting the table',
    ],
    [
      'Why does a hash table resize when its load factor gets high?',
      'To keep operations close to O(1)',
      'To sort its keys',
      'To save memory',
      'To remove duplicates',
    ],
    [
      'What does memoization cache?',
      "A function's results by its arguments",
      'Every variable assignment',
      'Compiled machine code',
      'The whole call stack',
    ],
    [
      'Bottom-up dynamic programming fills its table starting from...',
      'The smallest subproblems',
      'The final answer',
      'Random cells',
      'The largest subproblem',
    ],
    ['Coins {1, 3, 4}, amount 6: fewest coins needed?', '2', '3', '1', '4'],
    [
      'Timsort, used by Python, combines...',
      'Merge sort and insertion sort',
      'Quicksort and heapsort',
      'Bubble sort and selection sort',
      'Radix sort and counting sort',
    ],
    [
      "Which pivot choice makes quicksort's O(n²) case unlikely on sorted input?",
      'A random pivot',
      'The first element',
      'The last element',
      'The minimum element',
    ],
    [
      'Time to merge two sorted arrays of lengths n and m?',
      'O(n + m)',
      'O(n × m)',
      'O(log n)',
      'O(1)',
    ],
    [
      'Where is the minimum key in a binary search tree?',
      'The leftmost node',
      'The root',
      'The rightmost node',
      'Any leaf',
    ],
    [
      'Inserting 1, 2, 3, ..., n in order into a plain BST produces...',
      'A tree shaped like a linked list',
      'A perfectly balanced tree',
      'A heap',
      'A complete tree',
    ],
    [
      'A complete binary tree is filled...',
      'Level by level, left to right',
      'Only on the left side',
      'In random order',
      'Right to left from the bottom',
    ],
    [
      'Parent of index i (0-based) in an array heap?',
      '⌊(i - 1) / 2⌋',
      '2i + 1',
      'i - 1',
      '⌊i / 4⌋',
    ],
    [
      'Sifting one element down a binary heap takes...',
      'O(log n)',
      'O(1)',
      'O(n)',
      'O(n log n)',
    ],
    [
      'Space complexity of recursive binary search?',
      'O(log n)',
      'O(1)',
      'O(n)',
      'O(n log n)',
    ],
    [
      'Counting sort on n integers whose range is O(n) takes...',
      'O(n)',
      'O(n log n)',
      'O(n²)',
      'O(log n)',
    ],
    [
      'Which is slow on a hash map but fast on a balanced BST?',
      'Listing keys in sorted order',
      'Average lookup',
      'Average insert',
      'Average delete',
    ],
    [
      'The sliding window technique fits best with...',
      'Contiguous subarray or substring problems',
      'Tree traversals',
      'Graph colouring',
      'Sorting',
    ],
    [
      'Which traversal lists BST keys in descending order?',
      'Reverse in-order (right, root, left)',
      'Pre-order',
      'Post-order',
      'Level-order',
    ],
  ],
  4: [
    [
      'Which algorithm finds single-source shortest paths with non-negative weights?',
      "Dijkstra's",
      "Kruskal's",
      "Prim's",
      'Topological sort',
    ],
    [
      'Which shortest-path algorithm handles negative edge weights?',
      'Bellman-Ford',
      "Dijkstra's",
      "Prim's",
      "Kruskal's",
    ],
    [
      'A topological sort is only possible on a...',
      'Directed acyclic graph',
      'Undirected graph',
      'Complete graph',
      'Graph with a cycle',
    ],
    [
      "Which structure does Kruskal's algorithm use to detect cycles?",
      'Union-find',
      'Stack',
      'Trie',
      'Queue',
    ],
    [
      'Time complexity of BFS with an adjacency list (V vertices, E edges)?',
      'O(V + E)',
      'O(V × E)',
      'O(V²)',
      'O(E log V)',
    ],
    [
      'Building a heap from n unsorted elements takes...',
      'O(n)',
      'O(n log n)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Amortized cost of appending to a doubling dynamic array?',
      'O(1)',
      'O(n)',
      'O(log n)',
      'O(n log n)',
    ],
    [
      'What height does a red-black tree guarantee?',
      'O(log n)',
      'O(n)',
      'O(√n)',
      'O(1)',
    ],
    [
      'Which algorithm finds a cycle in a linked list with O(1) extra space?',
      "Floyd's tortoise and hare",
      "Dijkstra's",
      "Kadane's",
      "Kruskal's",
    ],
    [
      'Which algorithms build a minimum spanning tree?',
      "Prim's and Kruskal's",
      "Dijkstra's and A*",
      'BFS and DFS',
      'Bellman-Ford and Floyd-Warshall',
    ],
    [
      'How many edges does a spanning tree of V vertices have?',
      'V - 1',
      'V',
      'V + 1',
      '2V',
    ],
    [
      'Space used by an adjacency matrix for V vertices?',
      'O(V²)',
      'O(V + E)',
      'O(E)',
      'O(V log V)',
    ],
    [
      "Time complexity of Dijkstra's with a binary heap?",
      'O((V + E) log V)',
      'O(V + E)',
      'O(V³)',
      'O(V × E)',
    ],
    [
      'Time complexity of Bellman-Ford?',
      'O(V × E)',
      'O(V + E)',
      'O(E log V)',
      'O(log V)',
    ],
    [
      'How does Bellman-Ford detect a negative cycle?',
      'One more pass still shortens a distance',
      'Its queue empties early',
      'A vertex is visited twice',
      'An edge weight is zero',
    ],
    [
      'In an AVL tree, sibling subtree heights differ by at most...',
      '1',
      '0',
      '2',
      'log n',
    ],
    [
      'Which operation rebalances AVL and red-black trees?',
      'Rotation',
      'Rehashing',
      'Heapify',
      'Path compression',
    ],
    [
      'In a DFS of a directed graph, which edge type reveals a cycle?',
      'Back edge',
      'Tree edge',
      'Forward edge',
      'Cross edge',
    ],
    [
      "Kahn's topological sort starts from vertices with...",
      'In-degree 0',
      'The highest degree',
      'A self-loop',
      'Exactly one outgoing edge',
    ],
    [
      'Time to look up a word of length m in a trie?',
      'O(m)',
      'O(1)',
      'O(m²)',
      'O(2ᵐ)',
    ],
    [
      'B-trees are mainly designed for...',
      'Disk-based storage such as databases',
      'Shortest paths in graphs',
      'String prefix matching',
      'Undo history',
    ],
    [
      'Which pair gives O(1) get and put in an LRU cache?',
      'Hash map + doubly linked list',
      'Binary heap + stack',
      'Sorted array + queue',
      'Trie + stack',
    ],
    [
      "Time complexity of Kruskal's algorithm?",
      'O(E log E)',
      'O(V + E)',
      'O(V³)',
      'O(E²)',
    ],
    [
      'Two vertices in the same strongly connected component...',
      'Can reach each other',
      'Share no edges',
      'Have the same degree',
      'Are always adjacent',
    ],
    [
      'A graph is bipartite if and only if it has no...',
      'Odd-length cycle',
      'Even-length cycle',
      'Vertex of degree 1',
      'Path longer than 2',
    ],
    [
      'Which algorithm finds the maximum-sum contiguous subarray in O(n)?',
      "Kadane's",
      "Floyd's",
      "Prim's",
      'Binary search',
    ],
    [
      'Average time of quickselect for the k-th smallest element?',
      'O(n)',
      'O(n log n)',
      'O(log n)',
      'O(n²)',
    ],
    [
      "Dijkstra's algorithm can give wrong answers when the graph has...",
      'Negative edge weights',
      'Cycles',
      'Undirected edges',
      'More edges than vertices',
    ],
    [
      'Time complexity of the 0/1 knapsack DP with n items and capacity W?',
      'O(n × W)',
      'O(n + W)',
      'O(n log n)',
      'O(W log n)',
    ],
    [
      'Reversing the DFS finishing order of a DAG gives...',
      'A topological order',
      'A minimum spanning tree',
      'Shortest paths',
      'A BFS order',
    ],
    [
      'Merging k sorted lists of n total elements with a min-heap takes...',
      'O(n log k)',
      'O(n × k)',
      'O(k log n)',
      'O(n + k)',
    ],
    [
      'Worst-case hash table lookup when every key collides?',
      'O(n)',
      'O(1)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Time complexity of longest common subsequence DP on strings of length n and m?',
      'O(n × m)',
      'O(n + m)',
      'O(2ⁿ)',
      'O(n log m)',
    ],
    [
      'DFS-based topological sort runs in...',
      'O(V + E)',
      'O(V²)',
      'O(E log V)',
      'O(V × E)',
    ],
    [
      "Prim's algorithm with a binary heap runs in...",
      'O(E log V)',
      'O(V + E)',
      'O(V³)',
      'O(E²)',
    ],
    [
      'Maximum number of edges in a simple undirected graph with V vertices?',
      'V(V - 1) / 2',
      'V - 1',
      'V²',
      '2V',
    ],
    [
      'Which representation suits a sparse graph?',
      'Adjacency list',
      'Adjacency matrix',
      'Both use the same memory',
      'Neither can store it',
    ],
    [
      'Which representation checks whether edge (u, v) exists in O(1)?',
      'Adjacency matrix',
      'Adjacency list',
      'Edge list',
      'Sorted edge list',
    ],
    [
      'Union-find quickly answers...',
      'Are two elements in the same set?',
      'What is the shortest path?',
      'Is the array sorted?',
      'Which key is smallest?',
    ],
    [
      'How do you count connected components in an undirected graph?',
      'Run BFS or DFS from each unvisited vertex',
      'Binary search over the vertices',
      'Sort the edges by weight',
      'Build a heap of vertices',
    ],
    [
      'Longest path in a directed acyclic graph can be found in...',
      'O(V + E)',
      'O(2ⱽ)',
      'O(V!)',
      'O(Eⱽ)',
    ],
    [
      'Fewest-coins DP for amount A with k coin types runs in...',
      'O(A × k)',
      'O(A + k)',
      'O(kᴬ)',
      'O(A log k)',
    ],
    [
      'Time to insert into an AVL tree?',
      'O(log n)',
      'O(1)',
      'O(n)',
      'O(n log n)',
    ],
    [
      'In a red-black tree, the longest root-to-leaf path is at most ... the shortest.',
      'Twice',
      'Equal to',
      'Three times',
      'log n times',
    ],
    [
      'Worst-case time of a hash table insert that triggers a resize?',
      'O(n)',
      'O(1)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Amortized analysis gives...',
      'The average cost per operation over a worst-case sequence',
      'The best-case cost',
      'The expected cost on random inputs',
      'The cost of the first operation',
    ],
    [
      'Amortized dequeue cost of a queue built from two stacks?',
      'O(1)',
      'O(n)',
      'O(log n)',
      'O(n²)',
    ],
    [
      'Which structure gives every sliding window maximum in O(n) total?',
      'Monotonic deque',
      'Binary search tree',
      'Hash set',
      'Trie',
    ],
    [
      'A monotonic stack is typically used to find...',
      'The next greater element',
      'The median',
      'Shortest paths',
      'Duplicate keys',
    ],
    [
      "What does Dijkstra's algorithm pick at each step?",
      'The unvisited vertex with the smallest known distance',
      'The lightest edge in the graph',
      'A random neighbour',
      'The vertex with the most edges',
    ],
    [
      "Prim's algorithm grows the tree by adding...",
      'The cheapest edge leaving the tree',
      'The heaviest edge leaving the tree',
      'A random edge',
      'The edge with the most neighbours',
    ],
    [
      'Time to build a trie from words of total length L?',
      'O(L)',
      'O(L²)',
      'O(L log L)',
      'O(2ᴸ)',
    ],
    [
      'Finding the k smallest of n items by heapifying and popping k times takes...',
      'O(n + k log n)',
      'O(k)',
      'O(n²)',
      'O(k²)',
    ],
    [
      'Which problem needs DP because greedy choices fail?',
      '0/1 knapsack',
      'Fractional knapsack',
      'Activity selection',
      'Huffman coding',
    ],
    [
      'Huffman coding builds its tree using...',
      'A min-priority queue',
      'A stack',
      'A hash map',
      'A trie',
    ],
    [
      'Greedy activity selection picks the activity that...',
      'Finishes earliest',
      'Starts earliest',
      'Is the shortest',
      'Overlaps the most',
    ],
    [
      'Shortest paths in a DAG with negative weights, in O(V + E), come from...',
      'Relaxing edges in topological order',
      "Dijkstra's algorithm",
      "Prim's algorithm",
      'Plain BFS',
    ],
    [
      'A max-heap and a min-heap together can maintain a running...',
      'Median',
      'Sum',
      'Mode',
      'Product',
    ],
    [
      'DFS cycle detection in a directed graph marks vertices with...',
      'Three colours: unvisited, in progress, done',
      'Union-find sets',
      'BFS levels',
      'Edge weights',
    ],
  ],
  5: [
    [
      'Amortized cost of union-find with path compression and union by rank?',
      'O(α(n)), nearly constant',
      'O(log n)',
      'O(n)',
      'O(√n)',
    ],
    [
      'Time complexity of Floyd-Warshall all-pairs shortest paths?',
      'O(V³)',
      'O(V²)',
      'O(E log V)',
      'O(V + E)',
    ],
    [
      'Lower bound for comparison-based sorting?',
      'Ω(n log n)',
      'Ω(n)',
      'Ω(n²)',
      'Ω(log n)',
    ],
    [
      'Which structure handles prefix-sum queries and point updates in O(log n) each?',
      'Fenwick tree',
      'Trie',
      'Hash map',
      'Stack',
    ],
    [
      'Time for a range query on a segment tree?',
      'O(log n)',
      'O(1)',
      'O(n)',
      'O(n log n)',
    ],
    [
      'KMP string matching (text n, pattern m) runs in...',
      'O(n + m)',
      'O(n × m)',
      'O(n log m)',
      'O(m²)',
    ],
    [
      "What does KMP's failure function store for each prefix?",
      'Longest proper prefix that is also a suffix',
      'How often each character occurs',
      'A hash of the prefix',
      'The last mismatch position',
    ],
    [
      'By the master theorem, T(n) = 2T(n/2) + O(n) is...',
      'O(n log n)',
      'O(n)',
      'O(n²)',
      'O(log n)',
    ],
    [
      'By the master theorem, T(n) = T(n/2) + O(1) is...',
      'O(log n)',
      'O(1)',
      'O(n)',
      'O(n log n)',
    ],
    [
      'By the master theorem, T(n) = 4T(n/2) + O(n) is...',
      'O(n²)',
      'O(n log n)',
      'O(n)',
      'O(n² log n)',
    ],
    [
      "Time complexity of Tarjan's strongly connected components algorithm?",
      'O(V + E)',
      'O(V × E)',
      'O(V³)',
      'O(E log V)',
    ],
    [
      'Which of these problems is NP-complete?',
      'Boolean satisfiability (SAT)',
      'Shortest path',
      'Sorting',
      'Minimum spanning tree',
    ],
    [
      'Which of these is solvable in polynomial time?',
      '2-SAT',
      '3-SAT',
      'Hamiltonian cycle',
      'Subset sum',
    ],
    [
      'Held-Karp DP for the travelling salesman problem runs in...',
      'O(n² × 2ⁿ)',
      'O(n!)',
      'O(n³)',
      'O(2ⁿ)',
    ],
    [
      'The maximum flow in a network equals the capacity of the...',
      'Minimum cut',
      'Maximum cut',
      'Shortest path',
      'Minimum spanning tree',
    ],
    [
      'Edmonds-Karp finds augmenting paths with...',
      'BFS',
      'DFS',
      "Dijkstra's",
      'Random walks',
    ],
    [
      'Expected search time in a skip list?',
      'O(log n)',
      'O(1)',
      'O(n)',
      'O(√n)',
    ],
    [
      'Which structure answers static range-minimum queries in O(1) after O(n log n) preprocessing?',
      'Sparse table',
      'Fenwick tree',
      'Trie',
      'Binary heap',
    ],
    [
      'Space complexity of Floyd-Warshall?',
      'O(V²)',
      'O(V³)',
      'O(V + E)',
      'O(E)',
    ],
    [
      "What does A* search add to Dijkstra's algorithm?",
      'A heuristic estimate of the remaining cost',
      'Support for negative edges',
      'A second priority queue',
      'Random tie-breaking',
    ],
    [
      'Rabin-Karp string matching relies on...',
      'Rolling hashes',
      'Suffix trees',
      'A failure function',
      'Binary search',
    ],
    [
      'Which algorithm finds the longest palindromic substring in O(n)?',
      "Manacher's",
      "Kadane's",
      'KMP',
      "Kruskal's",
    ],
    [
      'Worst-case time of median-of-medians selection?',
      'O(n)',
      'O(n log n)',
      'O(n²)',
      'O(log n)',
    ],
    [
      'Longest increasing subsequence with patience sorting and binary search takes...',
      'O(n log n)',
      'O(n²)',
      'O(n)',
      'O(2ⁿ)',
    ],
    [
      'Finding bridges in an undirected graph relies on...',
      'DFS low-link values',
      'BFS levels',
      'Union-find',
      'A topological order',
    ],
    [
      'Matrix chain multiplication DP for n matrices runs in...',
      'O(n³)',
      'O(n²)',
      'O(2ⁿ)',
      'O(n log n)',
    ],
    [
      'Which heap supports decrease-key in O(1) amortized time?',
      'Fibonacci heap',
      'Binary heap',
      'Binomial heap',
      'd-ary heap',
    ],
    [
      "Dijkstra's with a Fibonacci heap runs in...",
      'O(E + V log V)',
      'O((V + E) log V)',
      'O(V × E)',
      'O(V³)',
    ],
    [
      'Amortized cost of an operation on a splay tree?',
      'O(log n)',
      'O(1)',
      'O(n)',
      'O(√n)',
    ],
    [
      'Lowest common ancestor queries with binary lifting take...',
      'O(log n) each',
      'O(1) each',
      'O(n) each',
      'O(√n) each',
    ],
    [
      'Which structure finds all pattern occurrences after O(n) preprocessing of the text?',
      'Suffix tree',
      'Binary heap',
      'Fenwick tree',
      'Union-find',
    ],
    [
      'What does the Z-array store at index i?',
      'Length of the longest substring at i that matches a prefix',
      'How often character i occurs',
      'A hash of the suffix at i',
      'The position of the next mismatch',
    ],
    [
      'Hopcroft-Karp finds a maximum bipartite matching in...',
      'O(E√V)',
      'O(V³)',
      'O(E log V)',
      'O(V + E)',
    ],
    [
      'The P vs NP question asks whether...',
      'Every quickly verifiable problem is quickly solvable',
      'Every problem is solvable',
      'Every program halts',
      'Sorting can beat O(n log n)',
    ],
    [
      'To prove a problem X is NP-hard, you reduce...',
      'A known NP-hard problem to X',
      'X to a known NP-hard problem',
      'X to sorting',
      'X to a problem in P',
    ],
    [
      'Which of these problems is undecidable?',
      'The halting problem',
      'Graph colouring',
      'SAT',
      'Travelling salesman',
    ],
    [
      'Lazy propagation in a segment tree speeds up...',
      'Range updates',
      'Point queries',
      'Building the tree',
      'Memory usage',
    ],
    [
      'Which structure finds the k-th smallest key in O(log n)?',
      'Order-statistic tree',
      'Hash map',
      'Stack',
      'Bloom filter',
    ],
    [
      'A Bloom filter can report...',
      'False positives, but no false negatives',
      'False negatives, but no false positives',
      'Both false positives and negatives',
      'Neither',
    ],
    [
      'Aho-Corasick (text n, total pattern length m, z matches) runs in...',
      'O(n + m + z)',
      'O(n × m)',
      'O(n log m)',
      'O(n × m + z)',
    ],
    [
      "Strassen's algorithm multiplies n × n matrices in about...",
      'O(n^2.81)',
      'O(n³)',
      'O(n²)',
      'O(n log n)',
    ],
    [
      'Karatsuba multiplies two n-digit numbers in about...',
      'O(n^1.58)',
      'O(n²)',
      'O(n log n)',
      'O(n)',
    ],
    [
      'Which algorithm finds strongly connected components with two DFS passes?',
      "Kosaraju's",
      "Kahn's",
      "Prim's",
      "Johnson's",
    ],
    [
      "Johnson's all-pairs shortest paths combines...",
      'Bellman-Ford reweighting with Dijkstra',
      'BFS with DFS',
      "Floyd-Warshall with Prim's",
      "Kruskal's with union-find",
    ],
    [
      'A treap combines...',
      'A BST on keys and a heap on random priorities',
      'A trie and a hash map',
      'A stack and a queue',
      'Two binary heaps',
    ],
    [
      'Bitmask DP over subsets of n items has about...',
      'O(2ⁿ) states',
      'O(n) states',
      'O(n²) states',
      'O(log n) states',
    ],
    [
      'Graham scan finds a convex hull in...',
      'O(n log n)',
      'O(n²)',
      'O(n)',
      'O(n³)',
    ],
    [
      'Which technique answers offline range queries by sorting them into √n blocks?',
      "Mo's algorithm",
      "Kadane's",
      "Manacher's",
      "Prim's",
    ],
    [
      'Square root decomposition answers a range query in...',
      'O(√n)',
      'O(1)',
      'O(n)',
      'O(n log n)',
    ],
    [
      "In a bipartite graph, König's theorem says minimum vertex cover equals...",
      'Maximum matching size',
      'Number of vertices',
      'Minimum spanning tree weight',
      'Number of edges',
    ],
    [
      'Knapsack is NP-hard, yet its DP runs in O(n × W). This is called...',
      'Pseudo-polynomial time',
      'Polynomial time',
      'Amortized time',
      'Constant time',
    ],
    [
      'Which structure keeps old versions by copying only O(log n) nodes per update?',
      'Persistent segment tree',
      'Hash map',
      'Circular buffer',
      'Array-based stack',
    ],
    [
      'Heavy-light decomposition lets any tree path cross...',
      'O(log n) chains',
      'O(1) chains',
      'O(n) chains',
      'O(√n) chains',
    ],
    [
      "Tarjan's offline lowest common ancestor algorithm uses...",
      'Union-find',
      'A segment tree',
      'A trie',
      'A Bloom filter',
    ],
  ],
};
